# List

In [28]:
peserta = {
    'Data science' : {'peserta' : 300, 'peserta_1' : 100, 'peserta_2' : 200},
    'UI/UX design' : {'peserta' : 220, 'peserta_1' : 100, 'peserta_2' : 120},
    'Agile development' : {'peserta' : 175, 'peserta_1' : 90, 'peserta_2' : 85},
    'Laravel development' : {'peserta' : 250, 'peserta_1' : 100, 'peserta_2' : 150},
    'Wordpress' : {'peserta' : 150, 'peserta_1' : 75, 'peserta_2' : 75}
}

def sanbercode(a):
  for k,v, in a.items():
    print('jumlah peserta {0} adalah {1} laki2 dan {2} perempuan' .format(k,v['peserta_2'],v['peserta_1']))

sanbercode(peserta)

jumlah peserta Data science adalah 200 laki2 dan 100 perempuan
jumlah peserta UI/UX design adalah 120 laki2 dan 100 perempuan
jumlah peserta Agile development adalah 85 laki2 dan 90 perempuan
jumlah peserta Laravel development adalah 150 laki2 dan 100 perempuan
jumlah peserta Wordpress adalah 75 laki2 dan 75 perempuan


In [52]:
List1 = [1,2,3,4,5]
List2 = [6,7,8,9,10]
#List2 = list(List1)
#List2 = List1[ : ]
#List2 = List1.copy()
#List2.copy() = List1
#List2 = List1 
#List2 = list(List1)
#List2 = List1
#List2.copy() = List1
List2



[1, 2, 3, 4, 5]

In [69]:
mainan = ['uno','remi','catur','monopoli','ludo']

def gaskeun():
  del mainan[0:1]
  return mainan
print(gaskeun())




['remi', 'catur', 'monopoli', 'ludo']


In [78]:
list1 = ['raka@gmail.com', 'yudi@gmail.com']
list2 = ['raka@gmail.com', 'yuda@gmail.com']
#list_new = [i for i in list1 and i in list2]
#list_new = [i for i in list1 and if in list2]
#list_new = [i for i in list1 if i in list2] #True
#list_new = [i for i in list2 and list1]
#list_new = [i for i in list1 and list2]
print(list_new)

['raka@gmail.com', 'yudi@gmail.com']


<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

**Jawaban:**

**Jenis data yang bisa dimasukan didalam List bisa berupa numeric, string, float, integer, boolean, dan lain-lain yang membuatnya heterogen. Hal ini menandakan bahwa list dapat memiliki semua jenis data dan dapat diulangi daftar data yang dimasukan di list menggunakan jenis loop apa pun.**

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
print([a, c, b])

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
print(a[1][-2:])

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p, reverse=False))
# get max value of list
print(max(p))

[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
b+a

[5, 1, 3, 1, 3, 5]

Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
# change list value
a[1][0] = 11
print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del(areas[8:10])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [ ]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [i for i in S if i % 2==0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key franche
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe ['itali'] = 'roma'

print('=== Check dict europe ===')
print(europe)

# cek apakah itali ada di dalam objek dictionary
print ('Expected Output:')
print('itali' in europe)

=== Check dict europe ===
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'itali': 'roma'}
Expected Output:
True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe ['germany'] = 'berlin'

# remove australia dari europa
europe.pop('australia') # bisa juga menggunakan del europe ['australia]

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country['indonesia'] = {'capital': 'jakarta', 'population' :250}

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for key in country:
    Daerah = country[key]['capital']
    print('Ibukota '+ key +' adalah '+ Daerah)

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta